/**
 * prebuild / pretypecheck step: generates `src/schema.ts` (gitignored) from
 * the Data API's OpenAPI document at https://docs.blockvectra.com/openapi/data.yaml.
 *
 * The output is a `.ts` (not `.d.ts`) file on purpose: `tsc` never copies
 * `.d.ts` inputs into `outDir`, so a `.d.ts` here would leave the published
 * `dist/index.d.ts` pointing at a declaration file that isn't shipped.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SPEC_URL = "https://docs.blockvectra.com/openapi/data.yaml";

async function main() {
  const ast = await openapiTS(new URL(SPEC_URL));
  const output = astToString(ast);

  const outFile = path.resolve(__dirname, "../src/schema.ts");
  const banner = "// Generated by `npm run generate:schema`. Do not edit by hand.\n";
  fs.writeFileSync(outFile, banner + output, "utf8");
  console.log(`wrote ${path.relative(process.cwd(), outFile)} from ${SPEC_URL}`);
}

main().catch((err: unknown) => {
  console.error(err);
  process.exitCode = 1;
});
